/**
 * KTC time-series forecast utilities — shared between DynastyForecast and TradeCalculator.
 *
 * Loads pre-computed forecasts from ktc-forecasts-{1qb,superflex}.json
 * (generated by scripts/train_ktc_timeseries.py with full feature vectors).
 */

// ── Types ────────────────────────────────────────────────────────────

export interface ForecastResult {
  horizon: number;
  value: number;
  logReturn: number;
  ciLow: number;
  ciHigh: number;
}

export interface PlayerForecastEntry {
  name: string;
  position: string;
  currentValue: number;
  forecasts: Record<string, {
    value: number;
    logReturn: number;
    ciLow: number;
    ciHigh: number;
  }>;
}

export interface ForecastCache {
  generatedAt: string;
  horizons: number[];
  format: string;
  players: Record<string, PlayerForecastEntry>;
}

export interface ModelCacheMetrics {
  position: string;
  horizon: number;
  n: number;
  cvR2: number | null;
  cvMae: number | null;
  cvScheme: string;
  cvR2PlayerGrouped: number | null;
  cvR2WalkForward: number | null;
  cvResidualStd: number | null;
  inSampleR2: number;
}

// ── Singleton loaders ────────────────────────────────────────────────

const _forecastPromises = new Map<string, Promise<ForecastCache | null>>();

export function loadForecasts(format: '1qb' | 'superflex' = '1qb'): Promise<ForecastCache | null> {
  if (!_forecastPromises.has(format)) {
    _forecastPromises.set(format,
      fetch(`${import.meta.env.BASE_URL}data/ktc-forecasts-${format}.json`)
        .then(r => r.ok ? r.json() as Promise<ForecastCache> : null)
        .catch(() => null)
    );
  }
  return _forecastPromises.get(format)!;
}

// ── Player forecast lookup ──────────────────────────────────────────

/** Get pre-computed forecasts for a player (by playerID) at all horizons. */
export function getPlayerForecasts(
  cache: ForecastCache,
  playerID: number,
): ForecastResult[] {
  const entry = cache.players[String(playerID)];
  if (!entry) return [];

  return cache.horizons.map(h => {
    const f = entry.forecasts[String(h)];
    if (!f) return null;
    return {
      horizon: h,
      value: f.value,
      logReturn: f.logReturn,
      ciLow: f.ciLow,
      ciHigh: f.ciHigh,
    };
  }).filter((f): f is ForecastResult => f !== null);
}

/** Get the projected value at a specific horizon (default 90 days). */
export function getProjectedValueFromCache(
  cache: ForecastCache,
  playerID: number,
  horizon = 90,
): number | null {
  const entry = cache.players[String(playerID)];
  if (!entry) return null;
  const f = entry.forecasts[String(horizon)];
  return f ? f.value : null;
}
