/**
 * KTC time-series forecast utilities — shared between DynastyForecast and TradeCalculator.
 *
 * Loads pre-computed forecasts from ktc-forecasts-{1qb,superflex}.json
 * (generated by scripts/train_ktc_timeseries.py with full feature vectors).
 */

// ── Types ────────────────────────────────────────────────────────────

export interface ForecastResult {
  horizon: number;
  value: number;
  logReturn: number;
  ciLow: number;
  ciHigh: number;
}

export interface PlayerForecastEntry {
  name: string;
  position: string;
  currentValue: number;
  forecasts: Record<string, {
    value: number;
    logReturn: number;
    ciLow: number;
    ciHigh: number;
  }>;
}

export interface ForecastCache {
  generatedAt: string;
  horizons: number[];
  format: string;
  players: Record<string, PlayerForecastEntry>;
}

export interface ModelCacheMetrics {
  position: string;
  horizon: number;
  n: number;
  cvR2: number | null;
  cvMae: number | null;
  cvScheme: string;
  cvR2PlayerGrouped: number | null;
  cvR2WalkForward: number | null;
  cvResidualStd: number | null;
  inSampleR2: number;
}

// ── Singleton loaders ────────────────────────────────────────────────

const _forecastPromises = new Map<string, Promise<ForecastCache | null>>();

export function loadForecasts(format: '1qb' | 'superflex' = '1qb'): Promise<ForecastCache | null> {
  if (!_forecastPromises.has(format)) {
    _forecastPromises.set(format,
      fetch(`${import.meta.env.BASE_URL}data/ktc-forecasts-${format}.json`)
        .then(r => r.ok ? r.json() as Promise<ForecastCache> : null)
        .catch(() => null)
    );
  }
  return _forecastPromises.get(format)!;
}

// ── Player forecast lookup ──────────────────────────────────────────

/** Get pre-computed forecasts for a player (by playerID) at all horizons. */
export function getPlayerForecasts(
  cache: ForecastCache,
  playerID: number,
): ForecastResult[] {
  const entry = cache.players[String(playerID)];
  if (!entry) return [];

  return cache.horizons.map(h => {
    const f = entry.forecasts[String(h)];
    if (!f) return null;
    return {
      horizon: h,
      value: f.value,
      logReturn: f.logReturn,
      ciLow: f.ciLow,
      ciHigh: f.ciHigh,
    };
  }).filter((f): f is ForecastResult => f !== null);
}

/** Get the projected value at a specific horizon (default 90 days). */
export function getProjectedValueFromCache(
  cache: ForecastCache,
  playerID: number,
  horizon = 90,
): number | null {
  const entry = cache.players[String(playerID)];
  if (!entry) return null;
  const f = entry.forecasts[String(horizon)];
  return f ? f.value : null;
}

// ── Redraft PPG (ML-predicted) ──────────────────────────────────────

import { loadPPGScores, loadCareerScores } from './modelScoreClient';

export type ScoringFormat = '1qb' | 'superflex' | 'tep';
export type TepLevel = 0 | 1 | 2 | 3; // 0=off, 1=TE+, 2=TE++, 3=TE+++

interface PPGEntry {
  ppg: number;
  recPG: number; // receptions per game (for TEP adjustment)
}

/** Lookup map: normalized "name|position" → PPGEntry */
export type RedraftLookup = Map<string, PPGEntry>;

function normalizeForJoin(name: string): string {
  return name.toLowerCase().replace(/[.\-']/g, '').replace(/\s+(jr|sr|ii|iii|iv|v)$/i, '').replace(/\s+/g, ' ').trim();
}

interface SupplementaryPlayer {
  name: string;
  position: string;
  ppg: number;
  recPG: number;
}

let _redraftPromise: Promise<RedraftLookup> | null = null;

/**
 * Build a unified PPG lookup merging three sources:
 * 1. score-store/ppg.json — ML-predicted PPG for 152 vets (primary)
 * 2. score-store/career.json — career model PPG for rookies
 * 3. redraft-projections.json — fallback PPG + recPG for TEP
 */
export function loadRedraftLookup(): Promise<RedraftLookup> {
  if (_redraftPromise) return _redraftPromise;
  _redraftPromise = (async () => {
    const map: RedraftLookup = new Map();

    // Load all sources in parallel
    const [ppgScores, careerScores, supplementary] = await Promise.all([
      loadPPGScores(),
      loadCareerScores(),
      fetch(`${import.meta.env.BASE_URL}data/redraft-projections.json`)
        .then(r => r.ok ? r.json() as Promise<{ players: SupplementaryPlayer[] }> : null)
        .catch(() => null),
    ]);

    // Layer 1: supplementary file (fallback PPG + recPG data for TEP)
    if (supplementary?.players) {
      for (const p of supplementary.players) {
        const key = `${normalizeForJoin(p.name)}|${p.position}`;
        map.set(key, { ppg: p.ppg, recPG: p.recPG });
      }
    }

    // Layer 2: career model predictions for recent draft classes (rookies)
    for (const c of careerScores) {
      if (c.draftSeason >= 2024 && c.predictedPPG > 0) {
        const key = `${normalizeForJoin(c.name)}|${c.position}`;
        const existing = map.get(key);
        map.set(key, { ppg: c.predictedPPG, recPG: existing?.recPG ?? 0 });
      }
    }

    // Layer 3: ML PPG predictions from score store (highest priority)
    for (const p of ppgScores) {
      const key = `${normalizeForJoin(p.name)}|${p.position}`;
      const existing = map.get(key);
      map.set(key, { ppg: p.predictedPPG, recPG: existing?.recPG ?? 0 });
    }

    return map;
  })();
  return _redraftPromise;
}

/** Look up a KTC player's redraft PPG, adjusted for scoring format.
 *  TEP: TEs get +0.5 per reception (TE Premium). */
export function getRedraftPPG(
  lookup: RedraftLookup,
  playerName: string,
  position: string,
  scoringFormat: ScoringFormat = '1qb',
): number | null {
  const key = `${normalizeForJoin(playerName)}|${position}`;
  const entry = lookup.get(key);
  if (!entry) return null;
  let ppg = entry.ppg;
  if (scoringFormat === 'tep' && position === 'TE') {
    ppg += 0.5 * entry.recPG; // TE Premium: +0.5 per reception
  }
  return ppg;
}

/**
 * TE Premium dynasty value multipliers derived from KTC's TE+/++/+++ tiers.
 * Empirical averages from KTC Superflex rankings (Apr 2026):
 *   TE+  ≈ 1.11x   TE++  ≈ 1.215x   TE+++  ≈ 1.32x
 */
export const TEP_MULTIPLIERS: Record<TepLevel, number> = {
  0: 1.0,
  1: 1.11,
  2: 1.215,
  3: 1.32,
};

export const TEP_LABELS: Record<TepLevel, string> = {
  0: 'Off',
  1: 'TE+',
  2: 'TE++',
  3: 'TE+++',
};
