/**
 * KTC time-series forecast utilities — shared between DynastyForecast and TradeCalculator.
 *
 * Loads pre-computed forecasts from ktc-forecasts-{1qb,superflex}.json
 * (generated by scripts/train_ktc_timeseries.py with full feature vectors).
 */

// ── Types ────────────────────────────────────────────────────────────

export interface ForecastResult {
  horizon: number;
  value: number;
  logReturn: number;
  ciLow: number;
  ciHigh: number;
}

export interface PlayerForecastEntry {
  name: string;
  position: string;
  currentValue: number;
  forecasts: Record<string, {
    value: number;
    logReturn: number;
    ciLow: number;
    ciHigh: number;
  }>;
}

export interface ForecastCache {
  generatedAt: string;
  horizons: number[];
  format: string;
  players: Record<string, PlayerForecastEntry>;
}

export interface ModelCacheMetrics {
  position: string;
  horizon: number;
  n: number;
  cvR2: number | null;
  cvMae: number | null;
  cvScheme: string;
  cvR2PlayerGrouped: number | null;
  cvR2WalkForward: number | null;
  cvResidualStd: number | null;
  inSampleR2: number;
}

// ── Singleton loaders ────────────────────────────────────────────────

const _forecastPromises = new Map<string, Promise<ForecastCache | null>>();

export function loadForecasts(format: '1qb' | 'superflex' = '1qb'): Promise<ForecastCache | null> {
  if (!_forecastPromises.has(format)) {
    _forecastPromises.set(format,
      fetch(`${import.meta.env.BASE_URL}data/ktc-forecasts-${format}.json`)
        .then(r => r.ok ? r.json() as Promise<ForecastCache> : null)
        .catch(() => null)
    );
  }
  return _forecastPromises.get(format)!;
}

// ── Player forecast lookup ──────────────────────────────────────────

/** Get pre-computed forecasts for a player (by playerID) at all horizons. */
export function getPlayerForecasts(
  cache: ForecastCache,
  playerID: number,
): ForecastResult[] {
  const entry = cache.players[String(playerID)];
  if (!entry) return [];

  return cache.horizons.map(h => {
    const f = entry.forecasts[String(h)];
    if (!f) return null;
    return {
      horizon: h,
      value: f.value,
      logReturn: f.logReturn,
      ciLow: f.ciLow,
      ciHigh: f.ciHigh,
    };
  }).filter((f): f is ForecastResult => f !== null);
}

/** Get the projected value at a specific horizon (default 90 days). */
export function getProjectedValueFromCache(
  cache: ForecastCache,
  playerID: number,
  horizon = 90,
): number | null {
  const entry = cache.players[String(playerID)];
  if (!entry) return null;
  const f = entry.forecasts[String(horizon)];
  return f ? f.value : null;
}

// ── Redraft projections ─────────────────────────────────────────────

export interface RedraftPlayer {
  name: string;
  position: string;
  ppg: number;       // actual 2025 per-game PPR output
  recPG: number;     // prior-season receptions per game (for TEP adjustment)
}

export interface RedraftProjections {
  season: number;
  generatedAt: string;
  scoring: string;
  players: RedraftPlayer[];
}

/** Lookup map: normalized "name|position" → RedraftPlayer */
export type RedraftLookup = Map<string, RedraftPlayer>;

export type ScoringFormat = '1qb' | 'superflex' | 'tep';

function normalizeForJoin(name: string): string {
  return name.toLowerCase().replace(/[.\-']/g, '').replace(/\s+(jr|sr|ii|iii|iv|v)$/i, '').replace(/\s+/g, ' ').trim();
}

let _redraftPromise: Promise<RedraftProjections | null> | null = null;

export function loadRedraftProjections(): Promise<RedraftProjections | null> {
  if (!_redraftPromise) {
    _redraftPromise = fetch(`${import.meta.env.BASE_URL}data/redraft-projections.json`)
      .then(r => r.ok ? r.json() as Promise<RedraftProjections> : null)
      .catch(() => null);
  }
  return _redraftPromise;
}

/** Build a lookup map from redraft projections, keyed by normalized "name|position". */
export function buildRedraftLookup(proj: RedraftProjections): RedraftLookup {
  const map: RedraftLookup = new Map();
  for (const p of proj.players) {
    const key = `${normalizeForJoin(p.name)}|${p.position}`;
    map.set(key, p);
  }
  return map;
}

/** Look up a KTC player's redraft PPG, adjusted for scoring format.
 *  TEP: TEs get +0.5 per reception (TE Premium). */
export function getRedraftPPG(
  lookup: RedraftLookup,
  playerName: string,
  position: string,
  scoringFormat: ScoringFormat = '1qb',
): number | null {
  const key = `${normalizeForJoin(playerName)}|${position}`;
  const entry = lookup.get(key);
  if (!entry) return null;
  let ppg = entry.ppg;
  if (scoringFormat === 'tep' && position === 'TE') {
    ppg += 0.5 * entry.recPG; // TE Premium: +0.5 per reception
  }
  return ppg;
}

/** TE Premium dynasty value boost: TEs are ~20% more valuable in TEP leagues. */
export const TEP_TE_DYNASTY_BOOST = 1.20;
