/**
 * Team-level projection engine.
 *
 * Uses a two-model ensemble when available:
 *   - Ridge delta model (predicts year-over-year volume changes)
 *   - LightGBM (predicts absolute volumes from 32 features)
 *   - Ensemble: 40% Ridge + 60% GBM
 *
 * Falls back to simple regression-to-mean blend when ensemble projections
 * are not available for the target season.
 *
 * Ensemble features include coaching/scheme data, Vegas lines, personnel
 * rates, O-line quality, and 2-year volume trends from the feature store.
 */

import type { SeasonTotals } from '../types';
import projectionConfig from '../generated/projection-config.json';

// Precomputed ensemble projections (generated by scripts/train_team_projections.py)
let ensembleProjections: Record<string, Record<string, number>> | null = null;
let ensembleSeason: number | null = null;

try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const tp = require('../generated/team-projections.json');
  ensembleProjections = tp.teams ?? null;
  ensembleSeason = tp.season ?? null;
} catch {
  // Ensemble projections not available — will fall back to blend
}

export interface TeamTotals {
  passAtt:  number;
  passYds:  number;
  passTD:   number;
  rushAtt:  number;
  rushYds:  number;
  rushTD:   number;
  recYds:   number;
  recTD:    number;
  targets:  number;
  receptions: number;
  totalTD:  number;
  pprPts:   number;
}

const KEYS: (keyof Omit<TeamTotals, 'totalTD' | 'pprPts'>)[] = [
  'passAtt', 'passYds', 'passTD',
  'rushAtt', 'rushYds', 'rushTD',
  'recYds',  'recTD',
  'targets', 'receptions',
];

function zero(): Omit<TeamTotals, 'totalTD' | 'pprPts'> {
  return {
    passAtt: 0, passYds: 0, passTD: 0,
    rushAtt: 0, rushYds: 0, rushTD: 0,
    recYds: 0,  recTD: 0,
    targets: 0, receptions: 0,
  };
}

function finalize(raw: Omit<TeamTotals, 'totalTD' | 'pprPts'>): TeamTotals {
  const totalTD = raw.passTD + raw.rushTD;
  const recs = raw.receptions > 0 ? raw.receptions : Math.round(raw.passAtt * 0.635);
  const pprPts = Math.round(
    raw.passYds * 0.04 + raw.passTD * 4 +
    raw.rushYds * 0.1  + raw.rushTD * 6 +
    recs * 1 + raw.recYds * 0.1 + raw.recTD * 6,
  );
  return { ...raw, totalTD, pprPts };
}

/**
 * Project team totals for the upcoming season.
 *
 * When ensemble projections are available for the target season, uses the
 * precomputed Ridge+GBM ensemble. Otherwise falls back to the simple
 * prior × teamWeight + leagueAvg × leagueWeight blend.
 */
export function projectTeamTotals(
  priorTotals: SeasonTotals[],
  teamWeight = projectionConfig.winner.teamWeight,
  targetSeason?: number,
): Map<string, TeamTotals> {
  // ── Try ensemble projections first ──
  if (ensembleProjections && targetSeason && targetSeason === ensembleSeason) {
    return buildFromEnsemble(priorTotals, ensembleProjections);
  }

  // ── Fallback: simple blend ──
  return buildFromBlend(priorTotals, teamWeight);
}

/**
 * Build team totals from precomputed ensemble projections.
 * Uses the ensemble for stats it covers, with blend fallback for recTD
 * (which the ensemble doesn't predict separately).
 */
function buildFromEnsemble(
  priorTotals: SeasonTotals[],
  ensemble: Record<string, Record<string, number>>,
): Map<string, TeamTotals> {
  // We still need prior data for recTD (not in ensemble) and as fallback
  const blendResult = buildFromBlend(priorTotals);

  const result = new Map<string, TeamTotals>();
  for (const [team, blended] of blendResult) {
    const ep = ensemble[team];
    if (!ep) {
      result.set(team, blended);
      continue;
    }

    const raw: Omit<TeamTotals, 'totalTD' | 'pprPts'> = {
      passAtt:    ep.passAtt    ?? blended.passAtt,
      passYds:    ep.passYds    ?? blended.passYds,
      passTD:     ep.passTD     ?? blended.passTD,
      rushAtt:    ep.rushAtt    ?? blended.rushAtt,
      rushYds:    ep.rushYds    ?? blended.rushYds,
      rushTD:     ep.rushTD     ?? blended.rushTD,
      recYds:     ep.recYds     ?? blended.recYds,
      recTD:      blended.recTD, // Not in ensemble, use blend
      targets:    ep.targets    ?? blended.targets,
      receptions: ep.receptions ?? blended.receptions,
    };
    result.set(team, finalize(raw));
  }
  return result;
}

/**
 * Simple blend: prior × teamWeight + leagueAvg × (1 - teamWeight).
 */
function buildFromBlend(
  priorTotals: SeasonTotals[],
  teamWeight = projectionConfig.winner.teamWeight,
): Map<string, TeamTotals> {
  const leagueWeight = 1 - teamWeight;

  const priorByTeam = new Map<string, ReturnType<typeof zero>>();
  for (const p of priorTotals) {
    const team = p.recent_team;
    if (!team) continue;
    if (!priorByTeam.has(team)) priorByTeam.set(team, zero());
    const t = priorByTeam.get(team)!;
    t.passAtt    += p.attempts          || 0;
    t.passYds    += p.passing_yards     || 0;
    t.passTD     += p.passing_tds       || 0;
    t.rushAtt    += p.carries           || 0;
    t.rushYds    += p.rushing_yards     || 0;
    t.rushTD     += p.rushing_tds       || 0;
    t.recYds     += p.receiving_yards   || 0;
    t.recTD      += p.receiving_tds     || 0;
    t.targets    += p.targets           || 0;
    t.receptions += p.receptions        || 0;
  }

  const n = priorByTeam.size || 1;
  const avg = zero();
  for (const t of priorByTeam.values()) {
    for (const k of KEYS) (avg as Record<string, number>)[k] += (t as Record<string, number>)[k];
  }
  for (const k of KEYS) (avg as Record<string, number>)[k] /= n;

  const result = new Map<string, TeamTotals>();
  for (const [team, prior] of priorByTeam) {
    const raw = zero();
    for (const k of KEYS) {
      (raw as Record<string, number>)[k] = Math.round(
        (prior as Record<string, number>)[k] * teamWeight +
        (avg   as Record<string, number>)[k] * leagueWeight,
      );
    }
    result.set(team, finalize(raw));
  }

  return result;
}
