import { useState, useEffect, useMemo } from 'react';
import { fetchPlayerBuzz, type BuzzSnapshot, type BuzzPlayer, type BuzzItem } from '../lib/buzz';
import { PlayerName } from './PlayerName';

type SortKey = 'volume' | 'sentiment' | 'trend' | 'recent';
const POS_FILTERS = ['ALL', 'QB', 'RB', 'WR', 'TE'] as const;
type PosFilter = typeof POS_FILTERS[number];

const POS_COLORS: Record<string, string> = { QB: '#6366f1', RB: '#10b981', WR: '#f59e0b', TE: '#ef4444' };

// Friendly source labels + colors for the volume breakdown + item tags.
const SOURCE_META: Record<string, { label: string; color: string }> = {
  espn: { label: 'ESPN', color: '#cc0000' },
  rotowire: { label: 'Rotowire', color: '#f59e0b' },
  'reddit:fantasyfootball': { label: 'r/ff', color: '#ff4500' },
  'reddit:dynastyff': { label: 'r/dynastyff', color: '#7c3aed' },
  'reddit:32beatwriters': { label: 'r/32beat', color: '#0ea5e9' },
};
const sourceMeta = (s: string) => SOURCE_META[s] ?? { label: s, color: 'var(--text-muted)' };

function sentimentColor(label: string): string {
  if (label === 'positive') return '#10b981';
  if (label === 'negative') return '#ef4444';
  return 'var(--text-muted)';
}

function relDate(iso?: string): string {
  if (!iso) return '';
  const ts = Date.parse(iso);
  if (Number.isNaN(ts)) return '';
  const days = Math.floor((Date.now() - ts) / 86400_000);
  if (days <= 0) return 'today';
  if (days === 1) return '1d ago';
  if (days < 7) return `${days}d ago`;
  return `${Math.floor(days / 7)}w ago`;
}

export function BuzzTracker() {
  const [snap, setSnap] = useState<BuzzSnapshot | null>(null);
  const [state, setState] = useState<'loading' | 'ready' | 'empty'>('loading');
  const [pos, setPos] = useState<PosFilter>('ALL');
  const [sort, setSort] = useState<SortKey>('volume');
  const [expanded, setExpanded] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetchPlayerBuzz().then((s) => {
      if (cancelled) return;
      if (!s || !s.players?.length) { setState('empty'); return; }
      setSnap(s);
      setState('ready');
    });
    return () => { cancelled = true; };
  }, []);

  const rows = useMemo(() => {
    if (!snap) return [];
    const filtered = pos === 'ALL' ? snap.players : snap.players.filter((p) => p.position === pos);
    const cmp: Record<SortKey, (a: BuzzPlayer, b: BuzzPlayer) => number> = {
      volume: (a, b) => b.volume - a.volume,
      sentiment: (a, b) => b.sentiment - a.sentiment,
      trend: (a, b) => b.trend - a.trend,
      recent: (a, b) => Date.parse(b.lastPublished ?? '') - Date.parse(a.lastPublished ?? ''),
    };
    return [...filtered].sort(cmp[sort]);
  }, [snap, pos, sort]);

  if (state === 'loading') {
    return <div style={{ padding: 24, color: 'var(--text-muted)' }}>Loading buzz…</div>;
  }
  if (state === 'empty') {
    return (
      <div style={{ padding: 24, maxWidth: 640 }}>
        <h2 style={{ fontSize: 18, margin: '0 0 8px' }}>Buzz Tracker</h2>
        <p style={{ color: 'var(--text-muted)', fontSize: 13, lineHeight: 1.6 }}>
          No buzz snapshot yet. It's generated by{' '}
          <code>scripts/fetch-player-buzz.ts</code> and refreshed on a cron
          (<code>.github/workflows/fetch-player-buzz.yml</code>). Run that
          workflow to populate the leaderboard.
        </p>
      </div>
    );
  }

  const maxVolume = Math.max(1, ...rows.map((r) => r.volume));

  return (
    <div style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 12 }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 14, flexWrap: 'wrap' }}>
        <h2 style={{ fontSize: 18, margin: 0 }}>Buzz Tracker</h2>
        <p style={{ fontSize: 12, color: 'var(--text-muted)', margin: 0 }}>
          Who's getting talked about over the last {snap?.windowDays ?? 14} days — news volume + sentiment
          from ESPN, Rotowire, and Reddit. Sentiment is keyword-scored (approximate).
        </p>
      </div>

      {/* Source legend */}
      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', fontSize: 11, color: 'var(--text-secondary)' }}>
        {(snap?.sources ?? []).map((s) => {
          const m = sourceMeta(s);
          return (
            <span key={s} style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
              <span style={{ width: 9, height: 9, borderRadius: 2, background: m.color, display: 'inline-block' }} />
              {m.label}
            </span>
          );
        })}
      </div>

      {/* Controls */}
      <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', alignItems: 'center' }}>
        <div style={{ display: 'inline-flex', border: '1px solid var(--border)', borderRadius: 6, overflow: 'hidden' }}>
          {POS_FILTERS.map((p) => (
            <button
              key={p}
              onClick={() => setPos(p)}
              style={{
                padding: '4px 12px', fontSize: 12, fontWeight: 600, border: 'none', cursor: 'pointer',
                background: pos === p ? '#6366f1' : 'transparent',
                color: pos === p ? '#fff' : 'var(--text-secondary)',
              }}
            >
              {p === 'ALL' ? 'All' : p}
            </button>
          ))}
        </div>
        <label style={{ fontSize: 12, color: 'var(--text-secondary)', display: 'inline-flex', gap: 6, alignItems: 'center' }}>
          Sort
          <select
            value={sort}
            onChange={(e) => setSort(e.target.value as SortKey)}
            style={{ fontSize: 12, padding: '3px 6px', background: 'var(--bg-secondary)', color: 'var(--text-primary)', border: '1px solid var(--border)', borderRadius: 4 }}
          >
            <option value="volume">Buzz volume</option>
            <option value="sentiment">Sentiment</option>
            <option value="trend">Trending up</option>
            <option value="recent">Most recent</option>
          </select>
        </label>
        <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>
          {rows.length} players · updated {relDate(snap?.generated)}
        </span>
      </div>

      {/* Leaderboard */}
      <div style={{ border: '1px solid var(--border)', borderRadius: 6, overflow: 'hidden' }}>
        {rows.map((p, i) => (
          <BuzzRow
            key={p.player_key ?? `${p.name}-${p.position}`}
            rank={i + 1}
            player={p}
            maxVolume={maxVolume}
            open={expanded === (p.player_key ?? p.name)}
            onToggle={() => setExpanded(expanded === (p.player_key ?? p.name) ? null : (p.player_key ?? p.name))}
          />
        ))}
      </div>
    </div>
  );
}

function BuzzRow({ rank, player, maxVolume, open, onToggle }: {
  rank: number; player: BuzzPlayer; maxVolume: number; open: boolean; onToggle: () => void;
}) {
  const sc = sentimentColor(player.sentimentLabel);
  const trendUp = player.trend > 1.15;
  const trendDown = player.trend > 0 && player.trend < 0.85;
  return (
    <div style={{ borderBottom: '1px solid var(--border)' }}>
      <div
        onClick={onToggle}
        style={{
          display: 'grid',
          gridTemplateColumns: '28px 1fr 90px 120px 64px 56px',
          alignItems: 'center', gap: 8, padding: '8px 12px', cursor: 'pointer',
          background: open ? 'var(--bg-tertiary)' : 'transparent',
        }}
      >
        <span style={{ color: 'var(--text-muted)', fontSize: 12, textAlign: 'right' }}>{rank}</span>
        <span style={{ display: 'flex', alignItems: 'baseline', gap: 8, minWidth: 0 }}>
          <span style={{ color: POS_COLORS[player.position] ?? 'var(--text-muted)', fontSize: 10, fontWeight: 700, width: 22 }}>{player.position}</span>
          <PlayerName name={player.name} playerKey={player.player_key} position={player.position} style={{ fontWeight: 600, fontSize: 13 }} />
          <span style={{ color: 'var(--text-muted)', fontSize: 11 }}>{player.team}</span>
          <span style={{ color: 'var(--text-muted)', fontSize: 11, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
            · {player.items[0]?.headline}
          </span>
        </span>
        {/* Volume + source breakdown bar */}
        <span title={`${player.volume} mentions`} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{ fontSize: 13, fontWeight: 700, fontVariantNumeric: 'tabular-nums', width: 18, textAlign: 'right' }}>{player.volume}</span>
          <span style={{ display: 'flex', height: 8, width: 56, borderRadius: 2, overflow: 'hidden', background: 'var(--bg-tertiary)' }}>
            {Object.entries(player.volumeBySource).map(([s, n]) => (
              <span key={s} title={`${sourceMeta(s).label}: ${n}`} style={{ background: sourceMeta(s).color, width: `${(n / player.volume) * 100}%` }} />
            ))}
          </span>
        </span>
        {/* Sentiment chip */}
        <span style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{ width: 56, height: 6, borderRadius: 3, background: 'var(--bg-tertiary)', position: 'relative', overflow: 'hidden' }}>
            <span style={{
              position: 'absolute', top: 0, bottom: 0,
              left: player.sentiment >= 0 ? '50%' : `${50 + player.sentiment * 50}%`,
              width: `${Math.abs(player.sentiment) * 50}%`, background: sc,
            }} />
          </span>
          <span style={{ fontSize: 11, color: sc, fontWeight: 600, width: 34 }}>
            {player.sentiment > 0 ? '+' : ''}{player.sentiment.toFixed(2)}
          </span>
        </span>
        {/* Trend */}
        <span style={{ fontSize: 12, color: trendUp ? '#10b981' : trendDown ? '#ef4444' : 'var(--text-muted)', textAlign: 'center' }}>
          {trendUp ? '▲' : trendDown ? '▼' : '—'} {player.trend.toFixed(1)}×
        </span>
        <span style={{ fontSize: 10, color: 'var(--text-muted)', textAlign: 'right' }}>{relDate(player.lastPublished)}</span>
      </div>

      {open && (
        <div style={{ padding: '4px 12px 12px 48px', display: 'flex', flexDirection: 'column', gap: 6 }}>
          {player.items.map((it, idx) => <BuzzItemRow key={idx} item={it} />)}
        </div>
      )}
    </div>
  );
}

function BuzzItemRow({ item }: { item: BuzzItem }) {
  const m = sourceMeta(item.source);
  const sc = sentimentColor(item.score >= 0.2 ? 'positive' : item.score <= -0.2 ? 'negative' : 'neutral');
  return (
    <div style={{ display: 'flex', gap: 8, alignItems: 'baseline', fontSize: 12 }}>
      <span style={{ color: m.color, fontWeight: 700, fontSize: 10, width: 72, flexShrink: 0 }}>{m.label}</span>
      <span style={{ flex: 1, minWidth: 0, color: 'var(--text-secondary)' }}>
        {item.link
          ? <a href={item.link} target="_blank" rel="noreferrer" style={{ color: 'var(--text-primary)', textDecoration: 'none' }}>{item.headline}</a>
          : item.headline}
        {item.summary && <span style={{ color: 'var(--text-muted)' }}> — {item.summary}</span>}
      </span>
      <span style={{ color: sc, fontSize: 10, fontWeight: 600, width: 34, textAlign: 'right', flexShrink: 0 }}>
        {item.score > 0 ? '+' : ''}{item.score.toFixed(2)}
      </span>
      <span style={{ color: 'var(--text-muted)', fontSize: 10, width: 52, textAlign: 'right', flexShrink: 0 }}>{relDate(item.published)}</span>
    </div>
  );
}
